[package]
name = "tvix_narinfo_thingamabob"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
nix-compat = { git = "https://code.tvl.fyi/depot.git:/tvix/nix-compat.git" }
rstest = { version = "0.18.2", default-features = false }

[profile.release]
lto = true
codegen-units = 1
strip = true
